version: '3.8'

services:
  app:
    container_name: 'pagopa-wallet-eventdispatcher'
    image: ${image}
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-wallet-net

networks:
  pagopa-wallet-net:
    driver: bridge
    external: true
