microservice-chart:
  namespace: "pay-wallet"
  nameOverride: ""
  fullnameOverride: "pagopa-pay-wallet-event-dispatcher-microservice"
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 10
    image:
      repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalleteventdispatcherservice
      tag: "latest"
    envConfig:
      OTEL_SERVICE_NAME: "pagopa-payment-wallet-event-dispatcher-service-blue"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-payment-wallet-event-dispatcher-service-blue,deployment.environment=uat"
    envSecret: {}
  image:
    repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalleteventdispatcherservice
    tag: "0.12.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "itnuat.pay-wallet.internal.uat.platform.pagopa.it"
    path: /pagopa-wallet-event-dispatcher-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "pay-wallet-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: 'uat'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    OTEL_SERVICE_NAME: "pagopa-payment-wallet-event-dispatcher-service"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.otel.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
    OTEL_INSTRUMENTATION_SPRING_SCHEDULING_ENABLED: "false"
    OTEL_INSTRUMENTATION_SPRING_INTEGRATION_ENABLED: "true"
    WALLET_STORAGE_QUEUE_ACCOUNT_NAME: pagopauitnpaywalletsa
    WALLET_STORAGE_QUEUE_ENDPOINT: https://pagopauitnpaywalletsa.queue.core.windows.net/pagopauitnpaywalletsa
    WALLET_USAGE_QUEUE_NAME: pagopa-u-itn-pay-wallet-usage-update-queue
    WALLET_SERVICE_URI: "http://pagopa-pay-wallet-microservice.pay-wallet.svc:8080"
    WALLET_SERVICE_READ_TIMEOUT: "10000"
    WALLET_SERVICE_CONNECTION_TIMEOUT: "10000"
    WALLET_EXPIRATION_QUEUE_NAME: "pagopa-u-itn-pay-wallet-expiration-queue"
    AZURE_EVENTHUB_TOPIC_NAME: "payment-wallet-ingestion-dl"
    AZURE_EVENTHUB_BOOTSTRAP_SERVER: "pagopa-u-itn-observ-evh.servicebus.windows.net:9093"
    CDC_SEND_RETRY_MAX_ATTEMPTS: "1"
    CDC_SEND_RETRY_INTERVAL_IN_MS: "1000"
    WALLET_CDC_QUEUE_NAME: "pagopa-u-itn-pay-wallet-cdc-queue"
    WALLET_CDC_QUEUE_POLLING_MAX_MESSAGE_PER_POLL: "30"
    WALLET_CDC_QUEUE_POLLING_FIXED_DELAY_MS: "1000"
    REDIS_HOST: pagopa-u-itn-pay-wallet-redis.redis.cache.windows.net
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    REDIS_STREAM_EVENT_CONTROLLER_STREAM_KEY: "wallet-event-dispatcher-commands"
    REDIS_STREAM_EVENT_CONTROLLER_CONSUMER_NAME_PREFIX: "event-dispatcher"
    EVENT_CONTROLLER_STATUS_POLLING_CHRON: "*/10 * * * * *"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    WALLET_STORAGE_QUEUE_KEY: wallet-storage-account-key
    AZURE_EVENTHUB_CONNECTION_STRING: sender-evt-tx-event-hub-connection-string
    REDIS_PASSWORD: redis-wallet-password
  keyvault:
    name: "pagopa-u-pay-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations:
    - effect: "NoSchedule"
      key: "paymentWalletOnly"
      operator: "Equal"
      value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - paywallet
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopapaymentwalleteventdispatcherservice
            namespaces: ["pay-wallet"]
            topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: 928bc159-85e9-4f09-ba08-1e71851166f1
