#microservice-chart:
#  namespace: "wallet"
#  image:
#    repository: pagopadcommonacr.azurecr.io/pagopapaymentwalleteventdispatcherservice
#    tag: "0.4.0"
#    pullPolicy: Always
#  livenessProbe:
#    httpGet:
#      path: /actuator/health/liveness
#      port: 8080
#    initialDelaySeconds: 120
#    failureThreshold: 6
#    periodSeconds: 10
#  readinessProbe:
#    httpGet:
#      path: /actuator/health/readiness
#      port: 8080
#    initialDelaySeconds: 120
#    failureThreshold: 6
#    periodSeconds: 10
#  deployment:
#    create: true
#  service:
#    create: true
#    type: ClusterIP
#    ports:
#      - 8080
#  ingress:
#    create: true
#    host: "weudev.wallet.internal.dev.platform.pagopa.it"
#    path: /pagopa-wallet-event-dispatcher-service/(.*)
#    servicePort: 8080
#  serviceAccount:
#    create: false
#    annotations: {}
#    name: ""
#  podAnnotations: {}
#  podSecurityContext:
#    seccompProfile:
#      type: RuntimeDefault
#  securityContext:
#    allowPrivilegeEscalation: false
#  resources:
#    requests:
#      memory: "512Mi"
#      cpu: "300m"
#    limits:
#      memory: "512Mi"
#      cpu: "300m"
#  autoscaling:
#    enable: true
#    minReplica: 1
#    maxReplica: 2
#    pollingInterval: 30 # seconds
#    cooldownPeriod: 300 # seconds
#    triggers:
#      - type: cpu
#        metadata:
#          # Required
#          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
#          value: "75"
#  envConfig:
#    ENV: 'dev'
#    APP_LOGGING_LEVEL: 'DEBUG'
#    DEFAULT_LOGGING_LEVEL: 'INFO'
#    OTEL_SERVICE_NAME: "pagopa-wallet-event-dispatcher-service"
#    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
#    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
#    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
#    OTEL_TRACES_EXPORTER: otlp
#    OTEL_METRICS_EXPORTER: otlp
#    OTEL_LOGS_EXPORTER: none
#    OTEL_TRACES_SAMPLER: "always_on"
#    WALLET_STORAGE_QUEUE_ACCOUNT_NAME: pagopadweuwalletsa
#    WALLET_STORAGE_QUEUE_ENDPOINT: https://pagopadweuwalletsa.queue.core.windows.net/pagopadweuwalletsa
#    WALLET_USAGE_QUEUE_NAME: pagopa-d-weu-wallet-usage-update-queue
#    WALLET_SERVICE_URI: "http://pagopawalletservice-microservice-chart.wallet.svc:8080"
#    WALLET_SERVICE_READ_TIMEOUT: "10000"
#    WALLET_SERVICE_CONNECTION_TIMEOUT: "10000"
#    WALLET_EXPIRATION_QUEUE_NAME: "pagopa-d-weu-wallet-expiration-queue"
#  envSecret:
#    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
#    WALLET_STORAGE_QUEUE_KEY: wallet-storage-account-key
#  keyvault:
#    name: "pagopa-d-wallet-kv"
#    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
#  nodeSelector: {}
#  tolerations: []
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: node_type
#                operator: In
#                values:
#                  - user
microservice-chart:
  image:
    tag: 0.7.0
