version: '3.8'

services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.29.0
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - $PWD/.data:/opt/azurite/folder
    networks:
      - pagopa-wallet-net

  azurite-init:
    container_name: azurite-init
    build:
      context: ..
      dockerfile: azurite/Dockerfile
    depends_on:
      - storage
    environment:
      QUEUE_WALLET_UPDATE: pagopa-wallet-usage-update-queue
    networks:
      - pagopa-wallet-net

networks:
  pagopa-wallet-net:
    driver: bridge
    external: false
